version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  auth-service:
    build: ./backend/auth-service
    ports:
      - "4001:4001"
      - "50051:50051"
    depends_on:
      - mongo
    env_file:
      - ./backend/auth-service/.env

  chat-service:
    build: ./backend/chat-service
    ports:
      - "4002:4002"
    depends_on:
      - auth-service
      - mongo
    env_file:
      - ./backend/chat-service/.env

  frontend:
    build: ./frontend/chat-ui
    ports:
      - "5173:80"
    depends_on:
      - chat-service
